package visoes;

import controles.ArmarioControle;
import java.util.List;
import modelos.Armario;
import respostas.CodigosResposta;
import respostas.RespostaGenerica;
import visoescomponentes.FormularioUI;
import visoescomponentes.ListagemUI;

public class ArmariosUI extends ListagemUI<Armario> {

    public ArmariosUI() {
        super();
    }

    @Override
    protected FormularioUI getTelaFormulario(Armario armarioEmEdicao) {
        return new ArmarioFormUI(armarioEmEdicao);
    }

    @Override
    protected void excluir(Armario excluir) {
        ArmarioControle.excluir(excluir);
    }

    @Override
    protected String[] getLinha(Armario armario) {
        return new String[]{armario.getNumero(), armario.getObservacoes()};
    }

    @Override
    protected List<Armario> buscarDados(String filtro) {
        RespostaGenerica<List<Armario>> resposta = ArmarioControle.buscarPaginavelPorFiltro(1, filtro);

        if (resposta.getCodigoResposta() != CodigosResposta.CODIGO_200_SUCESSO) {
            throw new Error();
        }

        return resposta.getData();
    }

    @Override
    protected String[] getCabecalhosColunas() {
        return new String[]{"Numero", "Obs"};
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
