package visoes;

import util.Coordenada;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.JFrame;
import javax.swing.LayoutStyle;


public class DesktopUI extends javax.swing.JFrame {

    /**
     * Creates new form DesktopUI
     */
    public DesktopUI() {
        setResizable(false);
        setUndecorated(true);
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }


    private static Coordenada getCentroTela(int larguraJanela, int alturaJanela) {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        return new Coordenada(
                (screenSize.width - larguraJanela) / 2,
                (screenSize.height - alturaJanela) / 2
        );

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Evaluation license - unknown
    private void initComponents() {
        desktopPane = new JDesktopPane();
        jPanel1 = new JPanel();
        devolverButton = new JButton();
        emprestarButton = new JButton();
        loginButton = new JButton();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new Dimension(1024, 768));
        var contentPane = getContentPane();

        //======== desktopPane ========
        {

            GroupLayout desktopPaneLayout = new GroupLayout(desktopPane);
            desktopPane.setLayout(desktopPaneLayout);
            desktopPaneLayout.setHorizontalGroup(
                desktopPaneLayout.createParallelGroup()
                    .addGap(0, 1038, Short.MAX_VALUE)
            );
            desktopPaneLayout.setVerticalGroup(
                desktopPaneLayout.createParallelGroup()
                    .addGap(0, 468, Short.MAX_VALUE)
            );
        }

        //======== jPanel1 ========
        {
            jPanel1.setBorder ( new javax . swing. border .CompoundBorder ( new javax . swing. border .TitledBorder ( new javax . swing
            . border .EmptyBorder ( 0, 0 ,0 , 0) ,  "JF\u006frmD\u0065sig\u006eer \u0045val\u0075ati\u006fn" , javax. swing .border . TitledBorder
            . CENTER ,javax . swing. border .TitledBorder . BOTTOM, new java. awt .Font ( "Dia\u006cog", java .
            awt . Font. BOLD ,12 ) ,java . awt. Color .red ) ,jPanel1. getBorder () ) )
            ; jPanel1. addPropertyChangeListener( new java. beans .PropertyChangeListener ( ){ @Override public void propertyChange (java . beans. PropertyChangeEvent e
            ) { if( "\u0062ord\u0065r" .equals ( e. getPropertyName () ) )throw new RuntimeException( ) ;} } )
            ;

            //---- devolverButton ----
            devolverButton.setText("DEVOLVER");
            devolverButton.addActionListener(e -> devolverButtonActionPerformed(e));

            //---- emprestarButton ----
            emprestarButton.setText("EMPRESTAR");
            emprestarButton.addActionListener(e -> emprestarButtonActionPerformed(e));

            //---- loginButton ----
            loginButton.setText("LOGIN");
            loginButton.addActionListener(e -> loginButtonActionPerformed(e));

            GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup()
                    .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addComponent(loginButton, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(devolverButton, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(emprestarButton, GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                        .addContainerGap())
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup()
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(emprestarButton, GroupLayout.PREFERRED_SIZE, 69, GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(devolverButton, GroupLayout.PREFERRED_SIZE, 69, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(loginButton, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
            );
        }

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                    .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(desktopPane))
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup()
                .addComponent(desktopPane)
                .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pack();
        setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents

    private void devolverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devolverButtonActionPerformed
        this.desktopPane.removeAll();
        repaint();
        DevolucaoUI devolucaoUI = new DevolucaoUI();

        Dimension devolucaoUISize = devolucaoUI.getSize();
        Coordenada coordenadaCentro = DesktopUI.getCentroTela(devolucaoUISize.width, devolucaoUISize.height);

        this.desktopPane.add(devolucaoUI);
        devolucaoUI.setLocation(coordenadaCentro.getPontoX(), coordenadaCentro.getPontoY());
        devolucaoUI.setVisible(true);
    }//GEN-LAST:event_devolverButtonActionPerformed

    private void emprestarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emprestarButtonActionPerformed
        this.desktopPane.removeAll();
        repaint();
        EmprestimoUI emprestimoUI = new EmprestimoUI();

        Dimension emprestimoUISize = emprestimoUI.getSize();
        Coordenada coordenadaCentro = DesktopUI.getCentroTela(emprestimoUISize.width, emprestimoUISize.height);

        this.desktopPane.add(emprestimoUI);
        emprestimoUI.setLocation(coordenadaCentro.getPontoX(), coordenadaCentro.getPontoY());
        emprestimoUI.setVisible(true);
    }//GEN-LAST:event_emprestarButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        LoginUI loginUI = new LoginUI();
        loginUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_loginButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Evaluation license - unknown
    private JDesktopPane desktopPane;
    private JPanel jPanel1;
    private JButton devolverButton;
    private JButton emprestarButton;
    private JButton loginButton;
    // End of variables declaration//GEN-END:variables
}
